export const SET_NEW_PATH = 'SET_NEW_PATH';
export const LOAD_ALL_POKEMONS = 'LOAD_ALL_POKEMONS';
export const LOAD_POKEMON_TO_FAVORITES = 'LOAD_POKEMON_TO_FAVORITES';
export const LOAD_SINGLE_POKEMON = 'LOAD_SINGLE_POKEMON';